### ISSUE TITLE
Address deprecation warnings in python 3.7

### ISSUE THREAD

**Issue by dkirkby** [jmeyers314/batoid#65]
The unit tests reveal two warnings.  The first requires replacing `yaml.load(...)` with `yaml.safe_load(...)`:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
The second is coming from `nbformat` and `past.types.oldstr` (?), so might mean I need to update my conda pkgs:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

**Comment by jmeyers314** [comment]
I think I've cleaned up the first warning now.  Looks like the second warning has been addressed [here](https://github.com/jupyter/nbformat/pull/130) and [here](https://github.com/PythonCharmers/python-future/pull/421) upstream, though maybe not in released versions yet.

**Comment by jmeyers314** [comment]
The yaml deprecation has indeed disappeared from the python3.7 travis run, so closing this.
